issues:
  exclude-rules:
    - text: 'Error return value of `uptrace.Shutdown` is not checked'
      linters:
        - errcheck
    - text: 'Drivers should implement'
      linters:
        - staticcheck
