package main

import (
	"context"
	"log"
	"os"

	"github.com/go-pg/pg/v10"
	"github.com/go-pg/pgext"
	"github.com/uptrace/uptrace-go/uptrace"
	"go.opentelemetry.io/otel/api/global"
)

var tracer = global.Tracer("go-pg-tracer")

func main() {
	ctx := context.Background()

	upclient := setupUptrace()
	defer upclient.Close()
	defer upclient.ReportPanic(ctx)

	options := &pg.Options{
		Addr:     "postgresql-server:5432",
		User:     "postgres",
		Database: "example",
	}
	db := pg.Connect(options)
	db.AddQueryHook(pgext.OpenTelemetryHook{})
	defer db.Close()

	err := createBookTable(ctx, db)
	if err != nil {
		upclient.ReportError(ctx, err)
		log.Println(err.Error())
		return
	}

	err = tracePgQueries(ctx, db)
	if err != nil {
		upclient.ReportError(ctx, err)
		log.Println(err.Error())
		return
	}
}

func setupUptrace() *uptrace.Client {
	if os.Getenv("UPTRACE_DSN") == "" {
		panic("UPTRACE_DSN is empty or missing")
	}

	hostname, _ := os.Hostname()
	upclient := uptrace.NewClient(&uptrace.Config{
		// copy your project DSN here or use UPTRACE_DSN enar
		DSN: "",

		Resource: map[string]interface{}{
			"host.name": hostname,
		},
	})

	return upclient
}

type Book struct {
	ID              int
	Title           string
	AuthorFirstName string
	AuthorLastName  string
}

func tracePgQueries(ctx context.Context, db *pg.DB) error {
	ctx, span := tracer.Start(ctx, "test-operations")
	defer span.End()

	book := &Book{
		Title:           "Harry Potter",
		AuthorFirstName: "Rowling",
		AuthorLastName:  "Joanne",
	}
	_, err := db.ModelContext(ctx, book).Insert()
	if err != nil {
		return err
	}

	_, err = db.ModelContext(ctx, book).
		Set("title = ?", "Harry Potter and the Deathly Hallows").
		Where("id = ?", book.ID).
		Update()
	if err != nil {
		return err
	}

	_, err = db.ModelContext(ctx, book).
		Where("id = ?", book.ID).
		Delete()
	if err != nil {
		return err
	}

	return nil
}

func createBookTable(ctx context.Context, db *pg.DB) error {
	_, err := db.ExecContext(ctx, "DROP TABLE IF EXISTS books")
	if err != nil {
		return err
	}

	cmd := `
		CREATE TABLE books (
			id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
			title varchar(500),
			author_last_name varchar(500),
			author_first_name varchar(500)
		);
	`
	_, err = db.ExecContext(ctx, cmd)
	if err != nil {
		return err
	}

	return nil
}
